jboss-fuse/fuse-components

camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.feature/feature.xml
camel-sap/org.fusesource.camel.component.sap.model.edit/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.model/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.test/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap/META-INF/MANIFEST.MF

in order to be aligned with the version declared in pom files.

Update MANIFEST version from 6.2.1 to 6.3.0

---

camel-sap/org.fusesource.camel.component.sap.model.edit/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.model/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap/META-INF/MANIFEST.MF

Fix version that are not aligned

---

camel-sap/org.fusesource.camel.component.sap.test/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.test/src/org/fusesource/camel/component/sap/util/RfcUtilTest.java
camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/util/RfcUtil.java

- previously throwing a NPE
- also set "integration" tests in @ ignore instead of commenting the
test annotation

#11 : Provide a better exception when the SAP Function is not found

---

camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.updatesite/pom.xml
camel-sap/camel-sap-repository/pom.xml
camel-sap/pom.xml

- Remote machien should have access to missin private repositories

Try to activate camel-sap-repository build

---

camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.updatesite/pom.xml

in order to publish onlyh the Master job and not all PRs

ENTESB-5616 - publish only with "publish" profile

---

camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.updatesite/pom.xml

release profile is currently used in perfectus build

Publish update site when release profile is activated

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapConstants.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapExchangePropertiesUtil.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapMessageHeadersUtil.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapSynchronousRfcConsumer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapSynchronousRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocListConsumer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalRfcConsumer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalRfcProducer.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/JCoTestSupport.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocListConsumerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocListProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocTestSupport.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapQueuedIDocListProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapQueuedIDocProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapQueuedRfcProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapSynchronousRfcConsumerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapSynchronousRfcProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapTransactionalRfcConsumerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapTransactionalRfcProducerTest.java
camel-sap/org.fusesource.camel.component.sap.test/data/testIDoc.xml
camel-sap/org.fusesource.camel.component.sap.test/data/testIDocs.xml

message header with SAP endpoint parameters and 
Exchange with Connection parameters.

[ENTESB-6250] Enhanced SAP endpoints to populate

---

camel-sap/pom.xml

Add JBoss repository to pom to retrieve JBoss Eclipse Target platform

---

camel-sap/org.fusesource.camel.component.sap.test/src/test/java/org/fusesource/camel/component/sap/util/IDocUtilTest.java
camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/util/IDocUtil.java

properly assign document reference to contained
segments.

[ENTESB-6772] Fixed document creation method to

---

camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/util/Util.java

methods to ensure packages are loaded in namespace
performing serialization.

[PATCH-1868] Added checks to all serialization

---

camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/util/Util.java

methods to ensure packages are loaded in namespace
performing serialization.

[ENTESB-6877] Added checks to all serialization

---

camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/Activator.java
camel-sap/org.fusesource.camel.component.sap/src/org/fusesource/camel/component/sap/util/Util.java

Fixes to ensure base packages are initialized and available to all referencing bundles of the SAP
Camel Component.

6.3.0.redhat r4

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/FunctionHandlerFactory.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/IDocHandlerFactory.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapRfcServerComponent.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocListServerComponent.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/ServerManager.java

code into new singleton ServerManager class. The 
set of all JCo Server instances, handling communication 
for inbound connections are now shared by all 
instances of SAP Camel components.

[ENTESB-6924] Refactored JCo Server management

---

camel-sap/camel-sap-component/pom.xml
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/DocumentConverterTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/JCoTestSupport.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocListProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapIDocProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapQueuedIDocListProducerTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/SapQueuedIDocProducerTest.java
camel-sap/org.fusesource.camel.component.sap.test/src/test/java/org/fusesource/camel/component/sap/util/RfcUtilTest.java
camel-sap/pom.xml

[ENTESB-7265] Updated camel-sap component to build

---

camel-sap/camel-sap-starter/pom.xml

Use build 000007.   Build 000011 has cycled out and been removed.

Use build 000007.   Build 000011 has cycled out and been removed.

---

activemq-karaf/pom.xml
activemq-karaf/src/main/resources/features.xml

https://issues.jboss.org/browse/ENTESB-7805
Thanks!

[ENTESB-7805] Let's rename the feature camel-activemq

---

activemq-karaf/pom.xml

Artifact can't depend on itself.

Artifact can't depend on itself.

---

camel-sap/camel-sap-component/src/main/resources/features.xml

Add a namespace to the features element in the features file.
https://issues.jboss.org/browse/ENTESB-7786

Add a namespace to the features file.

---

camel-activemq/pom.xml

https://issues.jboss.org/browse/ENTESB-7805
Thanks!

[ENTESB-7805] Let's exclude JMS 2 from camel-activemq

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapSynchronousRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentListConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/RequestConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/ResponseConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/StructureConverter.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/DocumentConverterRecoveryTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/JCoTestSupport.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/StructureConverterRecoveryTest.java

not blacklisted by the Camel type converter system when returning null
Objects.

[ENTESB-9115] Fixed Structure and Document converters so that they are

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapQueuedRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapSynchronousRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocListProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalIDocProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapTransactionalRfcProducer.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentListConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/RequestConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/ResponseConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/StructureConverter.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/DocumentConverterRecoveryTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/StructureConverterRecoveryTest.java

black listed by Camel type converter system

[PATCH-2685] Fixed SAP type converters from being

---

activemq-client/pom.xml
activemq-karaf/pom.xml
camel-activemq/pom.xml
camel-sap/camel-sap-component/pom.xml
camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.feature/feature.xml
camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.feature/pom.xml
camel-sap/camel-sap-repository/org.fusesource.camel.component.sap.updatesite/pom.xml
camel-sap/camel-sap-repository/pom.xml
camel-sap/camel-sap-starter/pom.xml
camel-sap/org.fusesource.camel.component.sap.model.edit/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.model.edit/pom.xml
camel-sap/org.fusesource.camel.component.sap.model/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.model/pom.xml
camel-sap/org.fusesource.camel.component.sap.test/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap.test/pom.xml
camel-sap/org.fusesource.camel.component.sap/META-INF/MANIFEST.MF
camel-sap/org.fusesource.camel.component.sap/pom.xml
camel-sap/pom.xml
pom.xml

Change version to 7.1.1

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/DocumentListConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/RequestConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/ResponseConverter.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/converter/StructureConverter.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/DocumentConverterRecoveryTest.java
camel-sap/camel-sap-component/src/test/java/org/fusesource/camel/component/sap/StructureConverterRecoveryTest.java
camel-sap/camel-sap-starter/pom.xml

failing to convert data. Updated SAP starter project pom to properly 
load JCo dependencies.

[ESTESB-9529] Modified SAP type converters to throw CamelException when

---

camel-sap/camel-sap-starter/pom.xml
camel-sap/pom.xml
pom.xml

Provides the hotfix branch with versions of camel/karaf that exist

Update poms with existing versions of camel/karaf

---

camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapClearCacheComponent.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapClearCacheEndpoint.java
camel-sap/camel-sap-component/src/main/java/org/fusesource/camel/component/sap/SapClearCacheProducer.java
camel-sap/camel-sap-component/src/main/resources/META-INF/services/org/apache/camel/component/sap-clear-cache

caches and  Data Layer registry.

[ENTESB-9716] Added endpoint type to camel-sap to clear JCo repository
